// <auto-generated />
using BlaiseApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlaiseApi.Migrations
{
    [DbContext(typeof(DBcontexto))]
    partial class DBcontextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlaiseApi.Models.Area", b =>
                {
                    b.Property<int>("AreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("bEstatus")
                        .HasColumnType("bit");

                    b.Property<string>("cDescripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("AreaId");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("BlaiseApi.Models.Correo", b =>
                {
                    b.Property<int>("CorreoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PersonalId")
                        .HasColumnType("int");

                    b.Property<bool>("bEstatus")
                        .HasColumnType("bit");

                    b.Property<string>("cCorreo")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("cPrincipal")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("CorreoId");

                    b.HasIndex("PersonalId");

                    b.ToTable("Correos");
                });

            modelBuilder.Entity("BlaiseApi.Models.Foto", b =>
                {
                    b.Property<int>("FotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PersonalId")
                        .HasColumnType("int");

                    b.Property<bool>("bEstatus")
                        .HasColumnType("bit");

                    b.Property<string>("cDescripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("cNom_Foto")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("cRuta")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.HasKey("FotoId");

                    b.HasIndex("PersonalId");

                    b.ToTable("Fotos");
                });

            modelBuilder.Entity("BlaiseApi.Models.Personal", b =>
                {
                    b.Property<int>("PersonalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TipoPersonalId")
                        .HasColumnType("int");

                    b.Property<bool>("bAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("bEstatus")
                        .HasColumnType("bit");

                    b.Property<string>("cContra")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("cNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("cNum_Empleado")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("cP_Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("cS_Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("PersonalId");

                    b.HasIndex("TipoPersonalId");

                    b.ToTable("Personals");
                });

            modelBuilder.Entity("BlaiseApi.Models.SubArea", b =>
                {
                    b.Property<int>("SubAreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("bEstatus")
                        .HasColumnType("bit");

                    b.Property<string>("cDescripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("SubAreaId");

                    b.ToTable("SubAreas");
                });

            modelBuilder.Entity("BlaiseApi.Models.TipoIncidentes", b =>
                {
                    b.Property<int>("TipoincidentesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("bEstatus")
                        .HasColumnType("bit");

                    b.Property<string>("cDescripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("TipoincidentesId");

                    b.ToTable("TipoIncidentes");
                });

            modelBuilder.Entity("BlaiseApi.Models.TipoPersonal", b =>
                {
                    b.Property<int>("TipoPersonalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SubAreaId")
                        .HasColumnType("int");

                    b.Property<bool>("bEstatus")
                        .HasColumnType("bit");

                    b.Property<string>("cDescripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("TipoPersonalId");

                    b.HasIndex("SubAreaId");

                    b.ToTable("TipoPersonals");
                });

            modelBuilder.Entity("BlaiseApi.Models.Turno", b =>
                {
                    b.Property<int>("TurnoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("bEstatus")
                        .HasColumnType("bit");

                    b.HasKey("TurnoId");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("BlaiseApi.Models.Correo", b =>
                {
                    b.HasOne("BlaiseApi.Models.Personal", "personal")
                        .WithMany()
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlaiseApi.Models.Foto", b =>
                {
                    b.HasOne("BlaiseApi.Models.Personal", "personal")
                        .WithMany()
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlaiseApi.Models.Personal", b =>
                {
                    b.HasOne("BlaiseApi.Models.TipoPersonal", "TipoPersonal")
                        .WithMany()
                        .HasForeignKey("TipoPersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlaiseApi.Models.TipoPersonal", b =>
                {
                    b.HasOne("BlaiseApi.Models.SubArea", "SubArea")
                        .WithMany()
                        .HasForeignKey("SubAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
